- hosts: localhost
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
  tasks:
  - name: Create host workstation 
    add_host:
       name: "workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}"
       group: workstation
       ansible_user: cloud-user
       ansible_ssh_private_key_file: ~/.ssh/openstack.pem

- hosts: workstation
  become: yes
  roles:
    - osp-instance-delete
