#adding task for lb-tier
- name: install haproxy
  yum:
    name: haproxy
    state: latest

- name: start haproxy at system restart
  service:
    name: haproxy
    state: started
    enabled: yes

- name: copy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy---


